from __future__ import annotations

import os
from abc import ABC, abstractmethod
from typing import Callable, List, Optional, Sequence, Union

from .ollama_install import DEFAULT_LOCAL_MODEL


class LLMClient(ABC):
    @abstractmethod
    def chat(self, messages: List[dict]) -> str:
        ...


class MockLLM(LLMClient):
    def __init__(
        self,
        responses: Union[Sequence[str], Callable[[List[dict]], str], None] = None,
        default: str = "[mock response]",
    ):
        self._queue = list(responses) if isinstance(responses, (list, tuple)) else None
        self._fn = responses if callable(responses) else None
        self.default = default
        self.calls: List[List[dict]] = []

    def chat(self, messages: List[dict]) -> str:
        self.calls.append(messages)
        if self._fn is not None:
            return self._fn(messages)
        if self._queue:
            return self._queue.pop(0)
        return self.default


class OllamaClient(LLMClient):
    def __init__(
        self,
        model: str = DEFAULT_LOCAL_MODEL,
        host: Optional[str] = None,
        api_key: Optional[str] = None,
    ):
        try:
            from dotenv import load_dotenv

            load_dotenv()
        except ImportError:
            pass

        try:
            from ollama import Client
        except ImportError as exc:
            raise RuntimeError(
                "the 'ollama' package is required for OllamaClient "
                "(pip install ollama)"
            ) from exc

        self.model = model
        api_key = api_key or os.environ.get("OLLAMA_API_KEY")
        host = host or os.environ.get("OLLAMA_HOST") or (
            "https://ollama.com" if api_key else "http://localhost:11434"
        )
        # Mirrors the wizard's two LLM setup modes exactly (write_env_api_key
        # vs. write_env_model in ollama_install.py): an API key means Ollama
        # Cloud, its absence means a local server. Recorded so audit records
        # (GuardedAgent.llm_provenance) can say which one actually answered.
        self.backend = "ollama_cloud" if api_key else "ollama_local"
        headers = {"Authorization": f"Bearer {api_key}"} if api_key else None
        self._client = Client(host=host, headers=headers)

    def chat(self, messages: List[dict]) -> str:
        response = self._client.chat(self.model, messages=messages)
        return response.message.content or ""


def resolve_llm(
    model: str,
    mock: bool,
    responses: Union[Sequence[str], Callable[[List[dict]], str], None] = None,
) -> tuple[LLMClient, dict]:
    """Monta o `LLMClient` que o `process` vai usar mais um registro de
    procedência dizendo o que de fato produziu o conteúdo — modelo real,
    simulação pedida, ou simulação por fallback: `REGISTRO`, "Texto movido do código".
    """
    if mock:
        return (
            MockLLM(responses, default="[mock response: no model available]"),
            {"kind": "mock_requested"},
        )
    try:
        llm = OllamaClient(model=model)
        llm.chat([{"role": "user", "content": "ping"}])
        return llm, {"kind": "real", "model": llm.model, "backend": llm.backend}
    except Exception as exc:
        return (
            MockLLM(default="[mock response: no model available]"),
            {
                "kind": "mock_fallback",
                # Qual modelo foi *pedido*: sem isso o registro diz que rodou simulação e não
                # diz em lugar de quê.
                "requested_model": model,
                "model_label": f"mock (fallback from {model})",
                "fallback_reason": f"{exc.__class__.__name__}: {exc}",
            },
        )


def describe_llm_provenance(provenance: dict) -> str:
    """One-line, user-facing summary of an `resolve_llm` provenance dict --
    printed by the CLI/GUI so a run's output always says what produced the
    content, not just when a fallback happens."""
    kind = provenance["kind"]
    if kind == "real":
        return f"[content generated by {provenance['model']} ({provenance['backend']})]"
    if kind == "mock_requested":
        return "[content simulated: mock requested]"
    if kind == "mock_fallback":
        # `.get` on requested_model, not `[...]`: records written before this
        # field existed are still read by the audit screen, and a KeyError
        # there would take the screen down over a missing label.
        pedido = provenance.get("requested_model")
        alvo = f"{pedido} unavailable" if pedido else "real model unavailable"
        return (
            f"[content simulated: {alvo} "
            f"({provenance['fallback_reason']}); using mock]"
        )
    raise ValueError(f"unknown llm provenance kind: {kind!r}")
