from __future__ import annotations

from ethical_agent import GuardedAgent, MockLLM
from ethical_agent.demo import DEMO_CASES, demo_scripted

from . import routing
from .dto import agent_result_summary
from .engine_factory import audit_notice_lines, build_audit, build_engine
from .errors import bad_request

NOTE = "(Responses generated by MockLLM; plug OllamaClient for a real model.)"


@routing.route(
    "POST", "/api/demo", realm="audit", requires_session=True, hidden_without_session=True
)
def post_demo(state, params, body):
    """Espelha o `demo` da CLI: os mesmos 7 prompts fixos compartilhados com o
    `cmd_demo`, sempre `MockLLM(demo_scripted)` — `REGISTRO`, "Texto movido do código".
    """
    config = body.get("config") or {}
    if not isinstance(config, dict):
        raise bad_request("invalid_request", "'config' must be an object")

    policy = config.get("policy", state.initial_config["policy"])
    ontology = config.get("ontology", state.initial_config["ontology"])
    grounding = config.get("grounding", state.initial_config["grounding"])
    norms = config.get("norms", state.initial_config["norms"])
    engine_kind = config.get("engine", state.initial_config["engine"])
    audit_log = config.get("audit_log", state.initial_config["audit_log"])

    try:
        engine = build_engine(policy, ontology, grounding, norms, engine_kind)
    except Exception as exc:  # noqa: BLE001 -- bad config path/JSON, not a server bug
        raise bad_request("engine_build_failed", f"{exc.__class__.__name__}: {exc}") from exc

    audit, init_warning = build_audit(audit_log, state.audit_lock)
    agent = GuardedAgent(engine=engine, llm=MockLLM(demo_scripted), audit=audit, source="demo")

    cases = []
    for text in DEMO_CASES:
        result = agent.process(text)
        case = agent_result_summary(result)
        case["text"] = text
        cases.append(case)

    return {
        "cases": cases,
        "audit_notices": audit_notice_lines(audit, init_warning),
        "note": NOTE,
    }
