from __future__ import annotations

from ethical_agent import GuardedAgent, MockLLM
from ethical_agent.demo import DEMO_CASES, demo_scripted

from . import routing
from .dto import agent_result_summary
from .engine_factory import audit_notice_lines, build_audit, build_engine
from .errors import bad_request

NOTE = "(Responses generated by MockLLM; plug OllamaClient for a real model.)"


@routing.route("POST", "/api/demo")
def post_demo(state, params, body):
    """Mirrors the CLI's `ethical_agent demo` / the former gui_app.py's
    DemoTab exactly: the same 7 fixed prompts (ethical_agent/demo.py, shared
    with cmd_demo -- not a third copy), always MockLLM(demo_scripted), never
    the web chat's interactive_mock_response (that one exists specifically
    so a *typed* conversation can reach all 5 intervention states; the demo
    script is fixed content, unrelated to what the visitor is doing).
    source="demo" is what lets the audit trail (and this server's own
    /api/chat/history sidebar) tell these apart from real usage.
    """
    config = body.get("config") or {}
    if not isinstance(config, dict):
        raise bad_request("invalid_request", "'config' must be an object")

    policy = config.get("policy", state.initial_config["policy"])
    ontology = config.get("ontology", state.initial_config["ontology"])
    grounding = config.get("grounding", state.initial_config["grounding"])
    norms = config.get("norms", state.initial_config["norms"])
    engine_kind = config.get("engine", state.initial_config["engine"])
    audit_log = config.get("audit_log", state.initial_config["audit_log"])

    try:
        engine = build_engine(policy, ontology, grounding, norms, engine_kind)
    except Exception as exc:  # noqa: BLE001 -- bad config path/JSON, not a server bug
        raise bad_request("engine_build_failed", f"{exc.__class__.__name__}: {exc}") from exc

    audit, init_warning = build_audit(audit_log, state.audit_lock)
    agent = GuardedAgent(engine=engine, llm=MockLLM(demo_scripted), audit=audit, source="demo")

    cases = []
    for text in DEMO_CASES:
        result = agent.process(text)
        case = agent_result_summary(result)
        case["text"] = text
        cases.append(case)

    return {
        "cases": cases,
        "audit_notices": audit_notice_lines(audit, init_warning),
        "note": NOTE,
    }
